### ISSUE TITLE
error: Unknown Guild

### ISSUE THREAD

**Issue by cronner** [kariudo/homeassistant-discord-bot#18]
trying to add bot got these errors:

error: Unknown Guild
 url: "https://url........?with_counts=true"
 code: "10004"

      at new _DiscordAPIError (/usr/src/app/index.js:5994:7)
      at /usr/src/app/index.js:5734:15
note: missing sourcemaps for /usr/src/app/index.js
note: consider bundling with '--sourcemap' to get an unminified traces

You need to add it different than the readme: https://github.com/discord/discord-api-docs/issues/5840
and correct Privileged Gateway Intents?

**Comment by kariudo** [comment]
Are you sure you copied the "server's" ID for the Guild ID. I've confirmed with others the security is working as expected still.

**Comment by cronner** [comment]
yes, did as in the link provided and it worked taht way and is running now :)
